export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const UPDATE_BASIC_FORM = "UPDATE_BASIC_FORM";

